# XXVI. THE KNAPSACK PROBLEM 
So the input is given by n items.
Each item comes with a value, $V_i$, the more the better for us, and also a size, $W_i$. We're going to assume that both of these are non-negative, for the sizes we're going to make additional assumption that their integral. In addition to these two n numbers, we are given one more which is called the capacity, capital W, again we'll assume this is non-negative and an integer.
    
    n items  each has a value:
        - value/profit v_i    (non-negative)
        - size w_i            (non-negative and integral)
        - capacity W          (non-negative and integral)
    
The knapsack problem, the responsibility of an algorithm is to select a subset of the items.
What do we want? We want as much value as possible, so we want to maximize the sum of the values of the items that we select.
So what prevents us from picking everything? Well, the sum of the sizes of the items that we pick have to total to at most the capacity capital W.

### A Dynamic Programming Algorithm
For the knapsack problem however there's a sense in which sub-problems can be smaller. We have to reduce the capacity before looking up the corresponding optimal solution of a sub-problem. That is we're not just peeling off items, but we're also sort of peeling off parts of the knapsack capacity. Now, here is where we're going to use our assumption, that I told you at the beginning, at our input, that sizes are all integers, and that the knapsack capacity is an integer. So, the knapsack capacity starts at capital W. Every time we peel off some integer amount of capacity from it. So at all sub problems, we're going to be working with integral knapsack capacities. So therefore, in the worst case, you know, what are the various sub problems that might arise? Well, perhaps, each choice of a residual capacity, 0, 1, 2, all the way up to the original knapsack capacity, capital W. So now we're in great shape. In step two, we figured out exactly what subproblems we care about. In step one, we figured out a formula by which we can solve bigger subproblems given the solutions of smaller ones, so all that remains now is to write down a table and fill it in systematically using the recurrence, beginning with the smaller subproblems, ending up with the largest subproblems. In this algorithm, the array A that we're going to be filling in has two dimensions, in contrast to one dimension in the wave independence set problem. That's because our sub-problems have two different indices. We have to keep track of both of which set of items we're allowed to use, and also what capacity we need to respect. So the two independent varables indexing sub problems forces us to have a 2D array that we're going to go through now in a double four loop. So in the initialization step, we fill in all the entries, where i equals zero, where there's no items there, of course, the optimal solution value is zero, and then we just go through the sub problem systematically.

![SEQUENCE ALIGNMENT](images/10_knapsack.png)


### Running Time
They are for loop with indexed by both i and x, there are $n+1$ choices for i, there are capital $W+1$ choices for x. So that gives us theta of $n.W$ different sub-problems. And all we do for each is a single comparison amongst previously computed solutions.
 So we just do constant work per sub-problem, giving us the overall running time of n times capital W i.e. $O(n.W)$ 
 
 <table>
    <caption>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;THE KNAPSACK PROBLEM </caption>
    <tr> <td>$\textbf{Operation}$ </td> <td>	$\textbf{Running Time}$ <td> </tr>
    <tr> <td>overall running time </td>	<td>$O(n.W)$ <td> </tr>
</table>

In [38]:
%matplotlib inline
import networkx as nx
import heapq
import numpy as np
from matplotlib import pyplot as plt
import copy 

def knapsack_problem_tabular(value, weights, A):
    #print("value {}, weights {}, A {}".format(value, weights, A))
    r, c = A.shape
    for i in range(1, r):
        for x in range(c):
            #print("i: {}, x: {}".format(i,x))
            if A[i-1][x] != None:
                aexcluding = A[i-1][x]
            if weights[i-1] > x :
                aincluding = 0 
            else:
                aincluding = A[i-1][x - weights[i-1]] + value[i-1] 
            A[i][x] =max(aexcluding, aincluding)
    
    return A[r-1, c-1]
    
 
def reconstruction_algorithm(value, weights, A):
    V = [] # value added
    r, c = A.shape
    r, c = r-1, c-1
    while r>0 and c>0:
        #print("r :{} , c: {} weights[r-1]: {} A[r][c]: {} ".format(r, c ,weights[r-1] ,A[r][c]))
        if weights[r-1] > c:
            if A[r][c] == A[r-1][c]:
                r -= 1
                continue
        if ( A[r][c] - value[r-1] ) == A[r-1][c-weights[r-1]]:
            #print("r :{} , c: {} weights[r]: {} A[r][c]: {}, A[r-1][c-weights[r-1]]: {} ".format(r, c ,weights[r-1] ,A[r][c], A[r-1][c-weights[r-1]]))
            V.append(value[r-1])
            r -= 1
            c = c - weights[r-1]
            continue
        
        
            
    print("Value Set : {}".format(V))
    

    
def knapsack_problem(value, weights, W): 
    # value: profit  &  W: capacity
    A = np.full((len(value)+1, W+1), None)  # max weight
    A[0][:] = 0
    max_value = knapsack_problem_tabular(value, weights, A)
    print("A : {}\n\nMax Value of optimal solution: {}".format(A, max_value))
    reconstruction_algorithm(value, weights, A)
    
 


#knapsack_problem([3, 2, 4, 4], [4, 3, 2, 3], 6)    
knapsack_problem([1, 2, 5, 6], [2, 3, 4, 5], 8)
    

A : [[0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 1 1]
 [0 0 1 2 2 3 3 3 3]
 [0 0 1 2 5 5 6 7 7]
 [0 0 1 2 5 6 6 7 8]]

Max Value of optimal solution: 8
Value Set : [6, 5]


### Challenge problem
In this programming problem and the next you'll code up the knapsack algorithm.

Let's start with a warm-up. Download the text file below: knapsack1.txt

This file describes a knapsack instance, and it has the following format:

[knapsack_size][number_of_items]

[value_1] [weight_1]

[value_2] [weight_2]

...

For example, the third line of the file is "50074 659", indicating that the second item has value 50074 and size 659, respectively.

You can assume that all numbers are positive. You should assume that item weights and the knapsack capacity are integers.

What is the value of the optimal solution?

ADVICE: If you're not getting the correct answer, try debugging your algorithm using some small test cases.

In [37]:
import urllib3

def testcase():
    http = urllib3.PoolManager()
    r1 = http.request('GET', "https://d3c33hcgiwev3.cloudfront.net/_6dfda29c18c77fd14511ba8964c2e265_knapsack1.txt?Expires=1563494400&Signature=B5IusAy8gOo9ipLQXmS-JHmS50vXCLglT-14TnvdLmWD0SE5QZe4QpKjGC~rZwUHKcW9IFWKFLshqC-Jma5YuljF3JxkgnwvBuGpMAULeZEtSnOWXDR6JqKztMAMcw4ryZ8veKo2sctl7epP0znY-y~mtX1fQZ~439udvXLaljA_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A")
    IntegerMatrixStringJoin = r1.data.decode('utf8').split('\n')
    IntegerMatrixStringJoin.remove('')
    meta = IntegerMatrixStringJoin[0].split(' ')
    W = int(meta[0])
    n = int(meta[1])
    IntegerMatrixStringJoin.remove(IntegerMatrixStringJoin[0])
    v = []
    w = []
    for i in range(n):
        data = IntegerMatrixStringJoin[i].split(' ')
        v.append(int(data[0]))
        w.append(int(data[1]))
    return v, w, W


value, weights, W = testcase()
knapsack_problem(value, weights, W)


/Users/aishwaya/anaconda2/envs/python_3_6/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)


A : [[0 0 0 ... 0 0 0]
 [0 0 0 ... 16808 16808 16808]
 [0 0 0 ... 66882 66882 66882]
 ...
 [0 0 0 ... 2414601 2414601 2414601]
 [0 0 0 ... 2456923 2456923 2460644]
 [0 0 0 ... 2493893 2493893 2493893]]

Max Value of optimal solution: 2493893


### TODO:  Challenge problem

This problem also asks you to solve a knapsack instance, but a much bigger one.

Download the text file below: knapsack_big.txt

This file describes a knapsack instance, and it has the following format:

[knapsack_size][number_of_items]

[value_1] [weight_1]

[value_2] [weight_2]

...

For example, the third line of the file is "50074 834558", indicating that the second item has value 50074 and size 834558, respectively. As before, you should assume that item weights and the knapsack capacity are integers.

This instance is so big that the straightforward iterative implemetation uses an infeasible amount of time and space. So you will have to be creative to compute an optimal solution. One idea is to go back to a recursive implementation, solving subproblems --- and, of course, caching the results to avoid redundant work --- only on an "as needed" basis. Also, be sure to think about appropriate data structures for storing and looking up solutions to subproblems.

What is the value of the optimal solution?

ADVICE: If you're not getting the correct answer, try debugging your algorithm using some small test cases.

In [ ]:
import urllib3

def testcase2():
    http = urllib3.PoolManager()
    r1 = http.request('GET', "https://d3c33hcgiwev3.cloudfront.net/_6dfda29c18c77fd14511ba8964c2e265_knapsack_big.txt?Expires=1563494400&Signature=dMpWhJOGlSTLuDJ~8VSiaEPJT7LLSTbYi~NByE4yDJaGlL5cobwJinKuVfunNR9e~iLvyjSpEubNj4MY-RhqqSLQVzzUIOR5JwQMExVGqCjzPWdxP4tiPqlN-SQPgKRzIJNfo9pLRKYRZKw1UxuYLQI3hQQlN89gyg30xvgS0Vk_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A")
    IntegerMatrixStringJoin = r1.data.decode('utf8').split('\n')
    IntegerMatrixStringJoin.remove('')
    meta = IntegerMatrixStringJoin[0].split(' ')
    W = int(meta[0])
    n = int(meta[1])
    IntegerMatrixStringJoin.remove(IntegerMatrixStringJoin[0])
    v = []
    w = []
    for i in range(n):
        data = IntegerMatrixStringJoin[i].split(' ')
        v.append(int(data[0]))
        w.append(int(data[1]))
    return v, w, W


value, weights, W = testcase2()
knapsack_problem(value, weights, W)



Ans: 4243395

# XXVII. SEQUENCE ALIGNMENT
### Optimal Substructure
So, a bit more precisely, as input in this computational problem, we're given two strings. I'm going to call them capital X and capital Y. I'm going to use little x and little y to denote the individual characters of these strings. Let's say the first string capital X has linked M and the second string Y has linked N. In addition to the two input strings we assume we're given as input the values for the various types of penalties. So that we know exactly how much it costs each time we insert a gap. And for each possible mismatch, we need to know exactly what's the cost of that mismatch. In principle you could be given a penalty for matching a letter with itself, but typically that's going to be a penalty of zero. The space of feasible solutions are just the ways of inserting gaps into the two strings so that the results have equal length. I should emphasize that you're allowed to insert gaps into both of the strings. In the example, we only inserted into one of the two strings, but in general, you might have an input where one string is seven characters longer than the other, and it might turn out that in the optimal alignment, the best thing to do is insert three gaps at various places in the longer string, and ten gaps at various places into the shorter string. And the goal, of course is just to compute amongst all of the exponentially many alignments, the one that minimizes the total penalty, where total penalty is just the sum of individual penalties for the inserted gaps and the various mismatches.

So let's do a thought experiment. What does the optimal solution have to look like? And again, remember, this is exactly what it is that we're trying to compute but that's not going to stop us from reasoning about it. If someone handed to us on a silver platter the optimal solution, what would it have to look like? So consider any old pair of strings, capital X and capital Y, and an optimal alignment of them. Let's visualize this optimal alignment as follows. Let's write down the string X plus whatever gaps get inserted into it on top, and right beneath it we'll write down the string Y, with whatever gaps are inserted into it. These two things have exactly the same length.

       Consider the optimal alignment of X, Y and it's final position:
       
       ---------  X + gaps  ---------  -  
       ---------  Y + gaps  ---------  -  
                                       (Final Position)
       
There are 3 relevant possiblities for the contents of the final position. Let me explain my reasoning, let's start with the upper parts of the final position. observe that if that's a character of the string capital X, it can only be the very last character. It can only be little X sub N. That's because that's where this string ends. Now we don't know that little X sub N is in the final position, there might be a gap. Similarly, in the bottom part of this final position, there's two possibilities. There's a gap, or, if it's a character of y, it has to be the final character, little y, sub n. So that one seems to suggest four possibilities, two options for the top, two options for the bottom. But the hint of talking about relevant possibilities is that it's totally pointless to have two, a gap in both the top and the bottom. Why? Well the penalty for gaps is non-negative, so if we just deleted both of those gaps we'd get an even better alignment of X and Y. And in studying an optimal solution, we can therefore assume we never have two gaps in a common position. <br>
So that leaves exactly three cases:
- It could be there's no gaps at all, that in fact this alignment matches the character, little $x_m$, with little $y_n$.
- Or it could match the final character of capital X i.e. $x_m$, with a gap.
- Or it could match the final character of capital Y i.e. $y_n$ with a gap.

### A Dynamic Programming Algorithm
So I'll use the notation $P_{ij}$ for the value of the optimal solution to the corresponding sub problem, the one involving the prefix $X_i$ and the prefix $Y_j$ So for a given set of positive values for i and j, what is $P_{ij}$? Well, there are three possibilities. 
- Case one is where the final position of the optimal alignment doesn't have any gaps, so it matches the final character of $X_i$, that is little $x_i$ and the final character of the prefix capital $Y_j$, that is the character little $y_j$. It matches them together and just reuses an optimal alignment for the smaller strings, $X_{i-1}$ and $Y_{i-1}$.  
- Case two is where the last letter of the first string, that is little $x_i$ gets matched with a gap. And that case the penalty of the corresponding alignment is the penalty of a gap plus whatever the optimal alignment is of the first $i-1$ letter of capital $X$ plus the first $j$ letter of Capital $Y$. 
- The symmetrically case three we pay for a gap and then we pay whatever the optimal alignment is of all of the first $i$ letters of capital $X$ with the first $j$ menace one letters of $Y$. This is the case where the last letter of the second string gets matched with the gap in the final position of the optimal alignment.
So we know that the optimal solution has to look like one of these three things, we don't know which, so in the recurrence we'll just in effect do brute force search among the three outcomes. We just remember, we just choose the minimum of the three possibilities. So that's the formal recurrence. It's correctness really just follows immediately from the work we already did,understand what the optimal solution has to look like. 

$
\text{$P_{ij}$ = penalty of optimal alignment of $X_i$ and $Y_j$ }\\
\text{for all $i$ in $[1,m]$ and $j$ in $[1,n]$:}\\
P_{ij} = min
\begin{cases}
α_{x_i y_j} + P_{(i-1), (j-1)}\\
α_{gap} + P_{(i-1), j}\\
α_{gap} + P_{i, (j-1)}
\end{cases}
$

![SEQUENCE ALIGNMENT](images/9_sequence_alignment.png)




### Running Time
So, the running time is completely trivial to evaluate. In each iteration of this double four loop, we do a constant amount of work. We just need to look up three things in constant time and make a couple of comparisons. How many four loops are there? Well, M iterations of the outer four loop, N iterations of the inner four loop. So we suffer the product, M times N. That is, the running time is proportional to the product of the lengths of the two strings. 
 
 <table>
    <caption>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; SEQUENCE ALIGNMENT </caption>
    <tr> <td>$\textbf{Operation}$ </td> <td>    $\textbf{Running Time}$ <td> </tr>
    <tr> <td>overall running time </td> <td>$O(m.n)$ <td> </tr>
</table>

# XXVIII. OPTIMAL BINARY SEARCH TREES 
Solution of a perfectly balanced search tree, need not be the best search tree when frequency of access is non uniform. You might want to have unbalanced trees, like this chain if it gets extremely frequent searches, closer to the roots to have smaller search time. 

So capital $C_T$ will denote the average search time of a proposed search tree T. So we sum over each of the items $i$, we weight it by the probability or the frequency of it's access $P_i$, and then that gets multiplied by the search time required in the tree $T$ to find the item $i$.


The search time for a given key $i$ and a given tree $T$ is just the number of nodes you have to visit until you get to the one containing $i$. So if you think about it, that's exactly the depth of the node in this tree plus one ($d+1$). So for example, if you're lucky enough that the key is at the root, the depth of the root is zero, and we're counting that as a search time as one. So it's depth plus one. So, one minor point. It's going to be convenient for me to not insist that the PI's sum to one. Of course, if the $P_i$s were probabilities, they would sum to one. But I'm going to go ahead and allow them to be arbitrary positive numbers. And that, for the same reason, I'm going to sometimes call capital $C_T$, the weighted search time rather that the average search time, because I won't necessarily be assuming that the $P_i$s, sum to one. 

### A Dynamic Programming Algorithm 
![OPTIMAL BINARY SEARCH TREES ](images/8_optimalBST.png)


### Running Time
So, let's just follow the usual procedure.Let's just look at how many subproblems got to get solved and then how much work has to get done to solve each of those subproblems. So as far as the number of subproblems, it's all possible choices of i and j, where i is at most j, or in other words, it's essentially half of that n by ngrid. So this is roughly n squared over two, let's just call it theta of n squared, so a quadratic number of subproblems. Now, for each of the subproblems, we have to evaluate this recurrence, we have to evaulate the formula, which conceptually is a breadth-first search through the number of candidates that we've identified. And a disctinction between this dynamic programming algorithm and all of the other ones we've seen recently, sequence allignment, knapsack, computing independent set of the line graphs, is that it's actually kind of a lot of options for what the optimal solution can be. That is, our breadth-first search, for the first time, is not over a merely constant number of possibilities. We have to try every possible route, each of the items in our given subproblem is a candidate route and we try them all. So, given a start item of i and an end item of j, there's j minus i plus one total items and we have to do constant work for each one of those choices. So there will be subproblems, some subproblems that we can evaluate quickly and only say constant time if i and j are very close to each other, but for a constant fraction of thesubproblems we have to deal with, this is going to be linear time, theta of n time. So over all, that gives us a cubic running time, theta of n cubed. Alright, so I would say this running time is sort of okay, not great. So it is polynomial time, that's good. That's certainly way, way, way faster than enumerating all of the exponentially many possible binary search trees, so it blows away breath-first search. But it's not something I would call blazingly fast or for free primitive or anything like that. So you're going to be able be to solve problem sizes with n in the 100's, but probably not n in the 1000's. So that will cover some applications where you'd want to use this optimal binary search tree algorithm, but not all of them. So it's good for some things, but it's not a universal solution

 <table>
    <caption>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; OPTIMAL BINARY SEARCH TREES  </caption>
    <tr> <td>$\textbf{Operation}$ </td> <td>    $\textbf{Running Time}$ <td> </tr>
    <tr> <td>subproblems </td> <td>$O(n^2)$ <td> </tr>
    <tr> <td>time to compute A[i,j] </td> <td>$O(j - i)$ <td> </tr>
    <tr> <td>overall running time </td> <td>$O(n^3)$ <td> </tr>
</table>